name: Push

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: stable

      - name: Test
        run: make test

  vet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: stable

      - name: Vet
        run: make lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: stable

      - name: Build
        run: |
          make build

          # check golangci-lint can successfully load vischeck.so
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          echo package main > /tmp/dummy.go
          golangci-lint run --config=example.golangci.yaml /tmp/dummy.go
